dict = \
{
    "aeroplane": 4,
    "apple": 47,
    "backpack": 24,
    "banana": 46,
    "baseball bat": 34,
    "baseball glove": 35,
    "bear": 21,
    "bed": 59,
    "bench": 13,
    "bicycle": 1,
    "bird": 14,
    "boat": 8,
    "book": 73,
    "bottle": 39,
    "bowl": 45,
    "broccoli": 50,
    "bus": 5,
    "cake": 55,
    "car": 2,
    "carrot": 51,
    "cat": 15,
    "cell phone": 67,
    "chair": 56,
    "clock": 74,
    "cow": 19,
    "cup": 41,
    "diningtable": 60,
    "dog": 16,
    "donut": 54,
    "elephant": 20,
    "fire hydrant": 10,
    "fork": 42,
    "frisbee": 29,
    "giraffe": 23,
    "hair drier": 78,
    "handbag": 26,
    "horse": 17,
    "hot dog": 52,
    "keyboard": 66,
    "kite": 33,
    "knife": 43,
    "laptop": 63,
    "microwave": 68,
    "motorbike": 3,
    "mouse": 64,
    "orange": 49,
    "oven": 69,
    "parking meter": 12,
    "person": 0,
    "pizza": 53,
    "pottedplant": 58,
    "refrigerator": 72,
    "remote": 65,
    "sandwich": 48,
    "scissors": 76,
    "sheep": 18,
    "sink": 71,
    "skateboard": 36,
    "skis": 30,
    "snowboard": 31,
    "sofa": 57,
    "spoon": 44,
    "sports ball": 32,
    "stop sign": 11,
    "suitcase": 28,
    "surfboard": 37,
    "teddy bear": 77,
    "tennis racket": 38,
    "tie": 27,
    "toaster": 70,
    "toilet": 61,
    "toothbrush": 79,
    "traffic light": 9,
    "train": 6,
    "truck": 7,
    "tvmonitor": 62,
    "umbrella": 25,
    "vase": 75,
    "wine glass": 40,
    "zebra": 22
}